name: Build Docker Images

run-name: Build Docker Image | ${{ github.ref_name }}

on: 
  push:
    branches:
    - main

jobs:
  build-image:
  name: Docker image creation
  

stepes:
  - name: setup env
    runs-on: ubuntu-latest

  - name: checkout repositoty
    uses: actions/checkout@4

  - name: Creating Docker image
    runs: |
      echo "Image creation started"
      docker build -t myapp6 .
      echo "Image creation completed"