name: Docker build CI

run-name: Docker Build Image | ${{ github.ref_name}}

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
    docker-build:
      name: Build Docker image
      run-on: ubuntu-latest

      steps:
        - name: Checkput repository
          uses: actions/checkout@v4

        - name: Build Docker images
          run: |
            echo "starting Docker build"
            docker build -t mayapp:latest .
            echo "Docker image build completed successfully"
