name: Build Docker Images

run-name: Build Docker Image | ${{ github.ref_name }}

on: 
  push:
    branches:
    - main

jobs:
  build-image:
    name: Docker image creation
    runs-on: ubuntu-latest
  
    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: Creating Docker image
      run: |
        echo "Image creation started"
        docker build -t myapp6 .
        echo "Image creation completed"