name: Build Docker image

run-name: Build Dokcer image | ${{ github.ref_name }}

on:
  push:
    branches:
    - main

jobs:
  image-creation:
    name: Docker image create
    runs-on: unbuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: creating image
      run: |
        echo "Image creation started"
        docker build -t myapp7 .
        echo "image creation completed"