name: Build docker image workflow

run-name: Docker image creation | $ {{ github.ref_name }}

on:
  push:
    branches:
    - main

jobs:
  build-docker-image:
  - name: Setup node
    runs-on: ubuntu-latest

  steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: creating docker image
      run: | 
        echo "Image creation started."
        docker build -t myapp5:latest .
        echo "Image creation completed"